// This file was generated by the TCS compiler.
// Do not edit manually.

pub mod example {

    use wincode_derive::{SchemaRead, SchemaWrite};

    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, SchemaRead, SchemaWrite)]
    #[repr(u32)]
    pub enum Type {
        #[default]
        Flat = 0,
        Round = 1,
        Pointed = 2,
    }

    #[derive(Debug, Clone, PartialEq, Default, SchemaRead, SchemaWrite)]
    #[repr(C)]
    pub struct Color {
        pub red: u8,
        pub green: u8,
        pub blue: u8,
        pub alpha: u8,
    }

    impl Color {
        /// Serialize this value to bytes
        pub fn to_bytes(&self) -> Vec<u8> {
            wincode::serialize(self).expect("serialization should not fail")
        }

        /// Deserialize from bytes
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, wincode::ReadError> {
            wincode::deserialize(bytes)
        }
    }

    #[derive(Debug, Clone, PartialEq, Default, SchemaRead, SchemaWrite)]
    #[repr(C)]
    pub struct Brush {
        pub type_: Type,
        pub colors: Vec<Color>,
    }

    impl Brush {
        /// Serialize this value to bytes
        pub fn to_bytes(&self) -> Vec<u8> {
            wincode::serialize(self).expect("serialization should not fail")
        }

        /// Deserialize from bytes
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, wincode::ReadError> {
            wincode::deserialize(bytes)
        }
    }

    #[derive(Debug, Clone, PartialEq, Default, SchemaRead, SchemaWrite)]
    #[repr(C)]
    pub struct Layer {
        pub name: String,
        pub brushes: Vec<Brush>,
    }

    impl Layer {
        /// Serialize this value to bytes
        pub fn to_bytes(&self) -> Vec<u8> {
            wincode::serialize(self).expect("serialization should not fail")
        }

        /// Deserialize from bytes
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, wincode::ReadError> {
            wincode::deserialize(bytes)
        }
    }

    #[derive(Debug, Clone, PartialEq, Default, SchemaRead, SchemaWrite)]
    pub struct Canvas {
        pub client_id: Option<u32>,
        pub width: Option<u32>,
        pub height: Option<u32>,
        pub layers: Option<Vec<Layer>>,
    }

    impl Canvas {
        /// Serialize this value to bytes
        pub fn to_bytes(&self) -> Vec<u8> {
            wincode::serialize(self).expect("serialization should not fail")
        }

        /// Deserialize from bytes
        pub fn from_bytes(bytes: &[u8]) -> Result<Self, wincode::ReadError> {
            wincode::deserialize(bytes)
        }
    }
}
